### ISSUE TITLE
Feature Request: Option to configure which file(s) configuration are read from

### ISSUE THREAD

**Issue by Zache** [madskristensen/ProjectTaskRunner#1]
Because of the rapid pace of change and volatile state of Asp.Net/DNX ([like this](https://github.com/aspnet/Announcements/issues/69)) I've found myself forced back from the bleeding edge. Rewinding back was very hassle free except for one thing. If you have a `project.json` in a project directory then you will get all kinds of weird behavior trying to restore NuGet-packages. `

This of course wouldn't be a problem if it weren't for this excellent extension. we would just remove the file. But then we lose a lot of value!

Allowing this to be configurable by users allow developers of non-DNX solutions to still benefit from the Task Runner.

**Comment by madskristensen** [comment]
I'm not sure I follow. How does this extension play into the restore issues with rolling back/forward of DNX versions?

**Comment by Zache** [comment]
Let me try to clarify, this is my/our situation right now:
- We are taking a break from the DNX-train and developing our solution on Old Asp.Net/OWIN until we can deal things like the changes in hosting Environment.
- We still want to use the Task Runner Explorer and the excellent gulp integration in Visual Studio that this extension provides.
- If you don't have a project.json file in your project directory this extension gives an error
- If you have a project.json file in your project directory then you get issues with restoring packages due to Visual Studio trying to treat the project as a DNX-project

What I'm asking for is eating the :cake: and having it too: If this extension would accept configuration from another (fallback?) source then it would allow everyone to leverage it without moving to DNX.

**Comment by madskristensen** [comment]
I'm still not sure how the issue relates to this extension. Gulp integration in Task Runner Explorer works with any project type including MVC 5 and WebForms projects. Has nothing to do with this extension.

If the issue is specific to project.json confusing Visual Studio for non-ASP.NET 5 projects then it's a VS project system issue and should be opened at https://github.com/aspnet/tooling/issues

**Comment by Zache** [comment]
You are correct, it seems in all the mess and confusion of converting I missed some configuration that caused me to believe that a project.json was required by this tool. Thanks for the help, and super-mega-thanks for an excellent extension!
