### ISSUE TITLE
Annoying collapse/expand behavior when double clicking grouped tasks.

### ISSUE THREAD

**Issue by Bartmax** [madskristensen/ProjectTaskRunner#3]
Since (i guess) Task runner were created with single tasks in mind, extensions like this have a minor UI issue with task that have sub-tasks.

![image](https://cloud.githubusercontent.com/assets/3386797/10810556/419039f6-7de9-11e5-9dc4-cc4f1ad5c3f7.png)

In a scenario like the image above, double click on `prepublish` will do 2 things:
1. execute all sub taks
2. toggle (expand/collapse) the tree <sup>**(undesired)**</sub>

preventing the collapse/expand behavior on double click will be great. Not sure if this should be an issue on the https://github.com/aspnet/tooling repo instead.

**Comment by madskristensen** [comment]
This is a known bug that we are fixing soon. The fix will likely be in a canary build in December
